Workaround MSVC compiler error in promise_impl
Simply including boost/asio/experimental/promise.hpp results in compilation error (VS 17.4 toolset v143) that looks like a compiler error since the tuple header has clearly been included.
```
1>C:\.conan\7aa99f\1\include\boost\asio\experimental\impl\promise.hpp(61,1): error C2027: use of undefined type 'std::tuple<_Types...>' (compiling source file xxx)
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\utility(533,19): message : see declaration of 'std::tuple<_Types...>' (compiling source file xxx)
1>C:\.conan\7aa99f\1\include\boost\asio\experimental\impl\promise.hpp(173,2): message : see reference to class template instantiation 'boost::asio::experimental::detail::promise_impl<void(Ts...),Executor,Allocator>' being compiled (compiling source file xxx)
```

This is a workaround for that compiles.

See:
    https://developercommunity.visualstudio.com/t/use-of-undefined-type-std::tuplelt;_Ty/10342164